### ISSUE TITLE
HList concatenation

### ISSUE THREAD

**Issue by tvald** [gcanti/typelevel-ts#17]
Would `HList` concatenation be worth adding? It enables `tuple` concatenation, which was my primary motivation. :)

```
type A = [number, null]
type B = [string]
type AB = [number, null, string]

type HListConcat<L1 extends HList, L2 extends HList> = {
  T: L2
  F: HCons<Head<L1>, HListConcat<Tail<L1>, L2>>
}[IsHNil<L1>]

type YZ = HListToTuple<HListConcat<TupleToHList<A>, TupleToHList<B>>>

const foo1: AB = [1, null, 'a']
const foo2: YZ = foo1
const foo3: AB = foo2
```

**Comment by gcanti** [comment]
Sure, would you like to send a PR?

**Comment by gcanti** [comment]
ping @tvald

(I've got some cycles, I can add `HListConcat` if you don't have time)

**Comment by tvald** [comment]
Sorry, I lost track of this over the holidays. The above snippet should go most of the way, so feel free to add it yourself.
