### ISSUE TITLE
Add Clean

### ISSUE THREAD

**Issue by gcanti** [gcanti/typelevel-ts#2]
Motivation

```ts
type Clean<T> = Pick<T, keyof T>
type A = { a: string } & { b: number } & { c: boolean }
/*
type A = {
    a: string;
} & {
    b: number;
} & {
    c: boolean;
}
*/
type B = Clean<A>
/*
type B = {
    a: string;
    b: number;
    c: boolean;
}
*/
```

**Comment by aaronjensen** [comment]
Out of curiosity why did you end up implementing w/o `Pick`?

**Comment by gcanti** [comment]
oops, just cut and paste from the wrong file I guess :(

**Comment by aaronjensen** [comment]
Ah, I was just curious if there was some difference in practice.

**Comment by tycho01** [comment]
@aaronjensen: at the time I experienced [issues with a few types](https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-308052919) with it, but I may need to test more on that, never figured out what they were about. As a result I myself went back from ahejlsberg's 2.5 version to the older approach.
But yeah, I'd done some `Simplify` type that's exactly your `Clean`, haha. Don't usually use `&` over `Overwrite`, but it works when you know keys won't overlap I guess.
