### ISSUE TITLE
Use boolean literals rather than 'T' and 'F'

### ISSUE THREAD

**Issue by pelotom** [gcanti/typelevel-ts#41]
I'm curious why the string literals `'T'` and `'F'` are used for type level conditionals instead of the boolean literals `true` and `false`. Is this for legacy reasons? Obviously it would be a major backwards-breaking change, so maybe not worth it, but it seems odd.

**Comment by gcanti** [comment]
They can be used as keys in the following pattern (an ante litteram conditional type)

```ts
type A = {
  T: true
  F: false
}[Equals<string, string | null>]
```

**Comment by pelotom** [comment]
Ah, makes sense, thanks!
