### ISSUE TITLE
typings suggestions

### ISSUE THREAD

**Issue by amir-arad** [gcanti/typelevel-ts#6]
I have some patterns I use for typings in my code. I'd be glad to PR them into this project:

 - avoid https://github.com/Microsoft/TypeScript/issues/16931
```ts
 type Method<R = void> = (...args:any[]) => R;
 type Method0<R = void> = () => R;
 type Method1<T1, R = void> = (t1: T1) => R;
 type Method2<T1, T2, R = void> = (t1: T1, t2: T2) => R;
 type Method3<T1, T2, T3, R = void> = (t1: T1, t2: T2, t3: T3) => R;
 type Method4<T1, T2, T3, T4, R = void> = (t1: T1, t2: T2, t3: T3, t4: T4) => R;
// ... and so on
```
 - generic class, class decorator (sadly does not support `extends` keyword, and does not match abstract classes).
```ts
export type Class<T extends object> = new(...args: any[]) => T;
export type ClassDecorator<T extends object> = Method1<Class<T>, Class<T>>;
```

**Comment by gcanti** [comment]
@amir-arad what do you mean?

**Comment by amir-arad** [comment]
I suggest adding these types to the project's export, to improve type annotations

**Comment by amir-arad** [comment]
oh, I completely misjudged this project's context. my bad.
amazing code btw. I've leaned a lot from reading it!
